publisher:
  name: Publisher (contains apps)
  address: ''
  website: https://solanamobile.com
  email: hello@solanamobile.com
  media:
    - purpose: icon
      uri: ./media/publisher_icon.jpeg
app:
  name: App (contains releases)
  address: ''
  android_package: com.company.dapp
  urls:
    license_url: http://cdn.org/license.html
    copyright_url: http://cdn.org/copyright.html
    privacy_policy_url: http://cdn.org/privacy.html
    website: http://cdn.org
  media:
    - purpose: icon
      uri: ./media/app_icon.jpeg
release:
  address: ''
  media:
    - purpose: screenshot
      uri: ./media/app_screenshot.png
  files:
    - purpose: install
      uri: ./files/app-debug.apk
  catalog:
    en-US:
      name: This is a single release
      long_description: Some wonderful release notes, in long-form
      new_in_version: Something new in this version
      saga_features: Some information about saga specific features
solana_mobile_dapp_publisher_portal:
  google_store_package: com.company.dapp.otherpkg
  testing_instructions: >-
    Here are some steps informing Solana Mobile of how to test this dapp. You
    can specify multiple lines of instructions. For example, if a login is
    needed, you would add those details here.
